  version: "3"
services:
  wp:
    restart: always
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    environment:
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_CONFIG_EXTRA: |
        /* Preconfig */
        define('DISALLOW_FILE_EDIT', true);
        define('WP_POST_REVISIONS', '9');
        /* Multisiting */
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL',);
        define('DOMAIN_CURRENT_SITE', 'localhost');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', '1');
        define('WP_ALLOW_MULTISITE', true);
    ports:
      - "8000:80"
    volumes:
      - ./wp-app:/var/www/html
  wpcli:
    image: wordpress:cli
    user: xfs
    depends_on:
    - wp
    volumes:
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_USER: "${DB_USER}"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: wp_password
      UPLOAD_LIMIT: 50M
    ports:
      - "9000:80"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
    - ./db_data:/var/lib/mysql
volumes:
  db_data:
  wp_data:
